@baseUrl = http://localhost:3000

### Crear Alojamiento
POST {{baseUrl}}/alojamientos/crear
Content-Type: application/json

{
    "id_host": "63691c82-502a-4bf8-8b05-fd6cb30a3cb0",
    "titulo": "Titulo",
    "descripcion": "Descripcion",
    "precio": 100,
    "capacidad": 1,
    "ubicacion": "Ubicacion", 
    "servicios": [
        "WiFi",
        "Estacionamiento",
        "Piscina"
    ]
}

#--------------------------------------------------#

### Obtener todos los alojamientos
GET {{baseUrl}}/alojamientos/consulta

#--------------------------------------------------#
### Obtener alojamiento por ID
GET {{baseUrl}}/alojamientos/consulta
Content-Type: application/json

{
    "id": "5e67543b63ce4853b7912b484760a385"
}

#--------------------------------------------------#

### Actualizar alojamiento
PUT {{baseUrl}}/alojamientos/editar
Content-Type: application/json

{
    "id": "5e67543b63ce4853b7912b484760a385",
    "titulo": "Titulo Actualizado",
    "descripcion": "Descripcion Actualizada",
    "precio": 150,
    "capacidad": 2,
    "ubicacion": "Ubicacion Actualizada", 
    "servicios": [
        "WiFi",
        "Estacionamiento"
    ]
}

#--------------------------------------------------#

### Eliminar alojamiento
DELETE {{baseUrl}}/alojamientos/drop
Content-Type: application/json

{
    "id": "5e67543b63ce4853b7912b484760a385"
}