@baseUrl = http://localhost:3000


### Crear un nuevo usuario(Host)
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "usuario":"user",
    "password":"123",
    "nombre":"user",
    "id_rol":"1"
}

### Login de HOST
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "usuario":"user",
    "password":"123"
}

### Crear un nuevo usuario (Admin)
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "usuario":"DX",
    "password":"123",
    "nombre":"user",
    "id_rol":"2"
}

### Login de ADMIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "usuario":"DX",
    "password":"123"
}


### Crear un nuevo usuario
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "usuario":"XD",
    "password":"123",
    "nombre":"user",
    "id_rol":"3"
}

### Login de USUARIO
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "usuario":"XD",
    "password":"123"
}

###logout
POST {{baseUrl}}/auth/logout