@baseUrl = http://localhost:3000

### Crear una reseña
POST {{baseUrl}}/resenas/crear
Content-Type: application/json

{
  "id_usuario": "0319d745-e654-46f0-ae85-7e0b3b7360da",
  "id_aloja": "9efaefe7-50c6-469f-80e4-77e5cf6f9713",
  "rating": 5,
  "comentario": "Excelente lugar, muy recomendable.",
  "creado_en": "2024-06-15T10:00:00Z",
  "actualizado_en": "2024-06-15T10:00:00Z"
}

#--------------------------------------------------#

###conseguir todas las reseñas
GET {{baseUrl}}/resenas/consulta

#--------------------------------------------------#

###consultar reseña por id
GET {{baseUrl}}/resenas/consulta
Content-Type: application/json

{
  "id": "25bb36ed-62b7-4d54-88f1-24d3c46860f5"
}

#--------------------------------------------------#

### Editar una reseña
PUT {{baseUrl}}/resenas/editar
Content-Type: application/json

{
  "id": "25bb36ed-62b7-4d54-88f1-24d3c46860f5",
  "rating": 4,
  "comentario": "Muy buen lugar, pero podría mejorar en limpieza.",
  "actualizado_en": "2024-06-20T12:00:00Z"
}

#--------------------------------------------------#
### Eliminar una reseña
DELETE {{baseUrl}}/resenas/drop
Content-Type: application/json

{
  "id": "7ebf561d-1ce6-40dc-950e-aa7a9433e8c0"
}