@baseUrl = http://localhost:3000

### Crear Reserva
POST {{baseUrl}}/reservas/crear
Content-Type: application/json

{
    "id_usuario": "0319d745-e654-46f0-ae85-7e0b3b7360da",
    "id_aloja": "9efaefe7-50c6-469f-80e4-77e5cf6f9713",
    "fecha_inicio": "2024-07-01",
    "fecha_fin": "2024-07-10",
    "precio_total": 600,
    "cantidad_huespedes": 1
}

#--------------------------------------------------#

### Obtener todas las reservas
GET {{baseUrl}}/reservas/consulta

#--------------------------------------------------#

### Obtener reserva por ID
GET {{baseUrl}}/reservas/consulta
Content-Type: application/json

{
    "id": "f5782bbb-95d3-4e35-bf94-cfff1510820b"
}

#--------------------------------------------------#

### Actualizar reserva
PUT {{baseUrl}}/reservas/editar
Content-Type: application/json

{
  "id": "f5782bbb-95d3-4e35-bf94-cfff1510820b",
  "fecha_inicio": "2024-07-05",
  "fecha_fin": "2024-07-15",
  "cantidad_huespedes": 3,
  "estado": 1,
  "actualizado_en": "2024-06-25T12:00:00Z"
}


#--------------------------------------------------#

### Eliminar reserva

DELETE {{baseUrl}}/reservas/drop
Content-Type: application/json

{
    "id": "f5782bbb-95d3-4e35-bf94-cfff1510820b"
}
