@baseUrl = http://localhost:3000

### Obtener todos los usuarios
GET {{baseUrl}}/usuarios/consultar

#--------------------------------------------------#

### Obtener usuario por id
GET {{baseUrl}}/usuarios/consultarPorid
Content-Type: application/json

{
    "id":"30ca429d-a41a-464e-8b10-4d83d793a5ce"
}

#--------------------------------------------------#

### Obtener usuario por correo
GET {{baseUrl}}/usuarios/consultarPorcorreo
Content-Type: application/json

{
    "correo": "omar@example.com"
}

#--------------------------------------------------#

### Actualizar nombre del usuario usando el id
PUT {{baseUrl}}/usuarios/editar
Content-Type: application/json

{
    "id":"30ca429d-a41a-464e-8b10-4d83d793a5ce",
    "nombre": "Jelouwin",
    "status": 0
}

#--------------------------------------------------#

### Eliminar usuario usando el id
DELETE  {{baseUrl}}/usuarios/eliminar
Content-Type: application/json

{
    "id":"63691c82-502a-4bf8-8b05-fd6cb30a3cb0"
}

